    TMR0               EQU     001H
    PCL                EQU     002H
    STATUS             EQU     003H
    FSR                EQU     004H
    PORTA              EQU     005H
    PORTB              EQU     006H
    PCLATH             EQU     00AH
    INTCON             EQU     00BH
    PIR1               EQU     00CH
    TMR1L              EQU     00EH
    TMR1H              EQU     00FH
    T1CON              EQU     010H
    TMR2               EQU     011H
    T2CON              EQU     012H
    CCPR1L             EQU     015H
    CCPR1H             EQU     016H
    CCP1CON            EQU     017H
    RCSTA              EQU     018H
    TXREG              EQU     019H
    RCREG              EQU     01AH
    CMCON              EQU     01FH
    GEN0_START         EQU     020H
    GEN0_END           EQU     07FH
    OPTION_REG         EQU     081H
    PCL                EQU     082H
    STATUS             EQU     083H
    FSR                EQU     084H
    TRISA              EQU     085H
    TRISB              EQU     086H
    PCLATH             EQU     08AH
    INTCON             EQU     08BH
    PIE1               EQU     08CH
    PCON               EQU     08EH
    PR2                EQU     092H
    TXSTA              EQU     098H
    SPBRG              EQU     099H
    EEDATA             EQU     09AH
    EEADR              EQU     09BH
    EECON1             EQU     09CH
    EECON2             EQU     09DH
    VRCON              EQU     09FH
    GEN1_START         EQU     0A0H
    GEN1_END           EQU     0FFH
    TMR0               EQU     101H
    PCL                EQU     102H
    STATUS             EQU     103H
    FSR                EQU     104H
    PORTB              EQU     106H
    PCLATH             EQU     10AH
    INTCON             EQU     10BH
    GEN2_START         EQU     110H
    GEN2_END           EQU     17FH
    OPTION_REG         EQU     181H
    PCL                EQU     182H
    STATUS             EQU     183H
    FSR                EQU     184H
    TRISB              EQU     186H
    PCLATH             EQU     18AH
    INTCON             EQU     18BH
    GEN3_START         EQU     190H
    GEN3_END           EQU     1FFH
