    CH         EQU     0F9H
    CCAP0H     EQU     0FAH
    CCAP1H     EQU     0FBH
    CCAP2H     EQU     0FCH
    CCAP3H     EQU     0FDH
    CCAP4H     EQU     0FEH
    B          EQU     0F0H
    CL         EQU     0E9H
    CCAP0L     EQU     0EAH
    CCAP1L     EQU     0EBH
    CCAP2L     EQU     0ECH
    CCAP3L     EQU     0EDH
    CCAP4L     EQU     0EEH
    ACC        EQU     0E0H
    P1M2       EQU     0E2H
    P3M2       EQU     0E4H
    CCON       EQU     0D8H
    CMOD       EQU     0D9H
    CCAPM0     EQU     0DAH
    CCAPM1     EQU     0DBH
    CCAPM2     EQU     0DCH
    CCAPM3     EQU     0DDH
    CCAPM4     EQU     0DEH
    PSW        EQU     0D0H
    P1M1       EQU     0D4H
    P3M1       EQU     0D5H
    P4         EQU     0C0H
    SPCON      EQU     0C3H
    SPSTA      EQU     0C4H
    SPDAT      EQU     0C5H
    IPL0       EQU     0B8H
    P3         EQU     0B0H
    IE1        EQU     0B1H
    IPL1       EQU     0B2H
    IPH1       EQU     0B3H
    IPH0       EQU     0B7H
    IE0        EQU     0A8H
    CKCON1     EQU     0AFH
    AUXR1      EQU     0A2H
    P1         EQU     090H
    TCON       EQU     088H
    TMOD       EQU     089H
    TL0        EQU     08AH
    TL1        EQU     08BH
    TH0        EQU     08CH
    TH1        EQU     08DH
    CKCON0     EQU     08FH
    SP         EQU     081H
    DPL        EQU     082H
    DPH        EQU     083H
    PCON       EQU     087H

;---------- BIT POSITIONS --------------------------
