    W1CON      EQU     0F8H
    W1FH       EQU     0FAH
    W1FL       EQU     0FBH
    W1CH       EQU     0FCH
    W1CL       EQU     0FDH
    W1IC       EQU     0FEH
    B          EQU     0F0H
    ADCLK      EQU     0F2H
    ADCON      EQU     0F3H
    ADDL       EQU     0F4H
    ADDH       EQU     0F5H
    ADCF       EQU     0F6H
    ADCA       EQU     0F7H
    W0CON      EQU     0E8H
    W0MOD      EQU     0E9H
    W0FH       EQU     0EAH
    W0FL       EQU     0EBH
    W0CH       EQU     0ECH
    W0CL       EQU     0EDH
    W0IC       EQU     0EEH
    HSB        EQU     0EFH
    ACC        EQU     0E0H
    P3M2       EQU     0E4H
    W0R0H      EQU     0D9H
    W0R0L      EQU     0DAH
    W0R1H      EQU     0DBH
    W0R1L      EQU     0DCH
    W0R2H      EQU     0DDH
    W0R2L      EQU     0DEH
    PSW        EQU     0D0H
    FCON       EQU     0D1H
    P3M1       EQU     0D5H
    P4M1       EQU     0D6H
    W1R0H      EQU     0C9H
    W1R0L      EQU     0CAH
    P4         EQU     0C0H
    IPL0       EQU     0B8H
    P3         EQU     0B0H
    IPH0       EQU     0B7H
    IEN0       EQU     0A8H
    AUXR1      EQU     0A2H
    IOR        EQU     0A5H
    WDTRST     EQU     0A6H
    WDTPRG     EQU     0A7H
    OSCBFA     EQU     009H
    CKRL       EQU     097H
    TCON       EQU     088H
    TMOD       EQU     089H
    TL0        EQU     08AH
    TL1        EQU     08BH
    TH0        EQU     08CH
    TH1        EQU     08DH
    AUXR       EQU     08EH
    CKCON      EQU     08FH
    SP         EQU     081H
    DPL        EQU     082H
    DPH        EQU     083H
    CKSEL      EQU     085H
    OSSCON     EQU     086H
    PCON       EQU     087H

;---------- BIT POSITIONS --------------------------
