    B          EQU     0F0H
    ACC        EQU     0E0H
    PSW        EQU     0D0H
    SPCR       EQU     0D5H
    T2CON      EQU     0C8H
    T2MOD      EQU     0C9H
    RCAP2L     EQU     0CAH
    RCAP2H     EQU     0CBH
    TL2        EQU     0CCH
    TH2        EQU     0CDH
    IP         EQU     0B8H
    SADEN      EQU     0B9H
    P3         EQU     0B0H
    IPH        EQU     0B7H
    IE         EQU     0A8H
    SADDR      EQU     0A9H
    SPSR       EQU     0AAH
    P2         EQU     0A0H
    WDTRST     EQU     0A6H
    WDTCON     EQU     0A7H
    SCON       EQU     098H
    SBUF       EQU     099H
    P1         EQU     090H
    TCON       EQU     088H
    TMOD       EQU     089H
    TL0        EQU     08AH
    TL1        EQU     08BH
    TH0        EQU     08CH
    TH1        EQU     08DH
    AUXR       EQU     08EH
    CLKREG     EQU     08FH
    P0         EQU     080H
    SP         EQU     081H
    DP0L       EQU     082H
    DP0H       EQU     083H
    DP1L       EQU     084H
    DP1H       EQU     085H
    SPDR       EQU     087H
    PCON       EQU     087H

;---------- BIT POSITIONS --------------------------
