    B          EQU     0F0H
    SPSR       EQU     0E8H
    SPCR       EQU     0E9H
    SPDR       EQU     0EAH
    ACC        EQU     0E0H
    PSW        EQU     0D0H
    P1M0       EQU     0C2H
    P1M1       EQU     0C3H
    P3M0       EQU     0C6H
    P3M1       EQU     0C7H
    IP         EQU     0B8H
    SADEN      EQU     0B9H
    P3         EQU     0B0H
    IPH        EQU     0B7H
    IE         EQU     0A8H
    SADDR      EQU     0A9H
    AUXR1      EQU     0A2H
    WDTRST     EQU     0A6H
    WDTCON     EQU     0A7H
    SCON       EQU     098H
    SBUF       EQU     099H
    GPMOD      EQU     09AH
    GPLS       EQU     09BH
    GPIEN      EQU     09CH
    GPIF       EQU     09DH
    P1         EQU     090H
    TCONB      EQU     091H
    RL0        EQU     092H
    RL1        EQU     093H
    RH0        EQU     094H
    RH1        EQU     095H
    ACSR       EQU     097H
    TCON       EQU     088H
    TMOD       EQU     089H
    TL0        EQU     08AH
    TL1        EQU     08BH
    TH0        EQU     08CH
    TH1        EQU     08DH
    AUXR       EQU     08EH
    CLKREG     EQU     08FH
    P0         EQU     080H
    SP         EQU     081H
    DPL        EQU     082H
    DPH        EQU     083H
    PCON       EQU     087H

;---------- BIT POSITIONS --------------------------
