    IPL1       EQU     0F8H
    CH         EQU     0F9H
    CCAP0H     EQU     0FAH
    CCAP1H     EQU     0FBH
    B          EQU     0F0H
    ADCLK      EQU     0F2H
    ADCON      EQU     0F3H
    ADDL       EQU     0F4H
    ADDH       EQU     0F5H
    ADCF       EQU     0F6H
    IPH1       EQU     0F7H
    IEN1       EQU     0E8H
    CL         EQU     0E9H
    CCAP0L     EQU     0EAH
    CCAP1L     EQU     0EBH
    CCAP2L     EQU     0ECH
    CCAP3L     EQU     0EDH
    CCAP4L     EQU     0EEH
    ACC        EQU     0E0H
    CCON       EQU     0D8H
    CMOD       EQU     0D9H
    CCAPM0     EQU     0DAH
    CCAPM1     EQU     0DBH
    CCAPM2     EQU     0DCH
    CCAPM3     EQU     0DDH
    CCAPM4     EQU     0DEH
    PSW        EQU     0D0H
    FCON       EQU     0D1H
    EECON      EQU     0D2H
    FSTA       EQU     0D3H
    SPCON      EQU     0D4H
    SPSCR      EQU     0D5H
    SPDAT      EQU     0D6H
    T2CON      EQU     0C8H
    T2MOD      EQU     0C9H
    RCAP2L     EQU     0CAH
    RCAP2H     EQU     0CBH
    TL2        EQU     0CCH
    TH2        EQU     0CDH
    P4         EQU     0C0H
    IPL0       EQU     0B8H
    SADEN      EQU     0B9H
    P3         EQU     0B0H
    IPH0       EQU     0B7H
    IEN0       EQU     0A8H
    SADDR      EQU     0A9H
    P2         EQU     0A0H
    AUXR1      EQU     0A2H
    WDTRST     EQU     0A6H
    WDTPRG     EQU     0A7H
    SCON       EQU     098H
    SBUF       EQU     099H
    P1         EQU     090H
    TCON       EQU     088H
    TMOD       EQU     089H
    TL0        EQU     08AH
    TL1        EQU     08BH
    TH0        EQU     08CH
    TH1        EQU     08DH
    AUXR       EQU     08EH
    CKCON0     EQU     08FH
    P0         EQU     080H
    SP         EQU     081H
    DPL        EQU     082H
    DPH        EQU     083H
    PCON       EQU     087H

;---------- BIT POSITIONS --------------------------
