; --- 8051 register BIT fields ---
; IE
EA         EQU     0xAF
ES         EQU     0xAC
ET1        EQU     0xAB
EX1        EQU     0xAA
ET0        EQU     0xA9
EX0        EQU     0xA8
; IP 
PS         EQU     0xBC
PT1        EQU     0xBB
PX1        EQU     0xBA
PT0        EQU     0xB9
PX0        EQU     0xB8
; P3
RD         EQU     0xB7
WR         EQU     0xB6
T1         EQU     0xB5
T0         EQU     0xB4
INT1       EQU     0xB3
INT0       EQU     0xB2
TXD        EQU     0xB1
RXD        EQU     0xB0
; PSW
CY         EQU     0xD7
AC         EQU     0xD6
F0         EQU     0xD5
RS1        EQU     0xD4
RS0        EQU     0xD3
OV         EQU     0xD2
P          EQU     0xD0
; TCON
TF1        EQU     0x8F
TR1        EQU     0x8E
TF0        EQU     0x8D
TR0        EQU     0x8C
IE1        EQU     0x8B
IT1        EQU     0x8A
IE0        EQU     0x89
IT0        EQU     0x88
; SCON
SM0        EQU     0x9F
SM1        EQU     0x9E
SM2        EQU     0x9D
REN        EQU     0x9C
TB8        EQU     0x9B
RB8        EQU     0x9A
TI         EQU     0x99
RI         EQU     0x98
