    B          EQU     0F0H
    ACC        EQU     0E0H
    PSW        EQU     0D0H
    IP         EQU     0B8H
    SADEN      EQU     0B9H
    P3         EQU     0B0H
    IPH        EQU     0B7H
    IE         EQU     0A8H
    SADDR      EQU     0A9H
    P2         EQU     0A0H
    AUXR1      EQU     0A2H
    SCON       EQU     098H
    SBUF       EQU     099H
    P1         EQU     090H
    TCON       EQU     088H
    TMOD       EQU     089H
    TL0        EQU     08AH
    TL1        EQU     08BH
    TH0        EQU     08CH
    TH1        EQU     08DH
    CKCON      EQU     08FH
    P0         EQU     080H
    SP         EQU     081H
    DPL        EQU     082H
    DPH        EQU     083H
    PCON       EQU     087H

;---------- BIT POSITIONS --------------------------
